name: booking-micro

networks:
  booking-net:
    driver: bridge

services:
  discovery-service:
    build:
      context: .
      dockerfile: discovery-service/Dockerfile
    container_name: discovery-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xms128m -Xmx256m
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8761/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - booking-net

  api-gateway:
    build:
      context: .
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    depends_on:
      discovery-service:
        condition: service_healthy
      users-service:
        condition: service_healthy
      bookings-service:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI=http://discovery-service:8761/eureka
      - JAVA_OPTS=-Xms128m -Xmx256m
      - API_KEY_HEADER=X-API-Key
      - API_KEY_VALUE=sifra123
    ports:
      - "8085:8085"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8085/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - booking-net

  users-service:
    build:
      context: .
      dockerfile: users-service/Dockerfile
    container_name: users-service
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI=http://discovery-service:8761/eureka
      - JAVA_OPTS=-Xms128m -Xmx256m
    ports:
      - "8081:8081"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8081/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - booking-net

  bookings-service:
    build:
      context: .
      dockerfile: bookings-service/Dockerfile
    container_name: bookings-service
    depends_on:
      discovery-service:
        condition: service_healthy
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_URI=http://discovery-service:8761/eureka
      - JAVA_OPTS=-Xms128m -Xmx256m
    ports:
      - "8082:8082"
    healthcheck:
      test: [ "CMD", "curl", "-fsS", "http://localhost:8082/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 20
    networks:
      - booking-net