version: "3.9"
services:
  discovery-service:
    build: ./discovery-service
    container_name: discovery-service
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    depends_on:
      - discovery-service
    ports:
      - "8085:8085"
    environment:
      - SERVER_PORT=8085
      - JAVA_OPTS=-Xms128m -Xmx256m

  users-service:
    build: ./users-service
    container_name: users-service
    depends_on:
      - discovery-service
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - JAVA_OPTS=-Xms128m -Xmx256m

  bookings-service:
    build: ./bookings-service
    container_name: bookings-service
    depends_on:
      - discovery-service
      - users-service
    ports:
      - "8082:8082"
    environment:
      - SERVER_PORT=8082
      - JAVA_OPTS=-Xms128m -Xmx256m