server:
  port: 8085

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: users
          uri: lb://USERS-SERVICE
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1
        - id: bookings
          uri: lb://BOOKINGS-SERVICE
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=1
      default_filters: []
    loadbalancer:
      cache:
        enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

management:
  endpoints:
    web:
      exposure:
        include: health,info

security:
  api-key:
    enabled: true
    header-name: ${API_KEY_HEADER:X-API-Key}
    value: ${API_KEY_VALUE:sifra123}
    whitelist:
      - /actuator/**
      - /api/users/v3/api-docs/**
      - /api/users/swagger-ui/**
      - /api/bookings/v3/api-docs/**
      - /api/bookings/swagger-ui/**