server:
  port: 8085

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      routes:
        - id: users-route
          uri: lb://users-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=1

        - id: bookings-route
          uri: lb://bookings-service
          predicates:
            - Path=/api/bookings/**
          filters:
            - StripPrefix=1

      httpclient:
        connect-timeout: 2000
        response-timeout: 3s

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: false

security:
  api-key:
    header: X-API-Key
    value: sifra123
    whitelist:
      - /actuator/**
      - /api/users/swagger-ui/**
      - /api/users/v3/api-docs/**
      - /api/bookings/swagger-ui/**
      - /api/bookings/v3/api-docs/**

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized
